### ISSUE TITLE
devenv command fails if conda is not on path

### ISSUE THREAD

**Issue by oliveira-esss** [ESSS/conda-devenv#45]
I was just updating an env in a linux machine with `/full/path/to/conda devenv -f environment.devenv.yml` and got this traceback:
```
Traceback (most recent call last):
  File "/home/company/Work/miniconda/bin/conda-devenv", line 11, in <module>
    load_entry_point('conda-devenv==0.9.0', 'console_scripts', 'conda-devenv')()
  File "/home/company/Work/miniconda/lib/python2.7/site-packages/conda_devenv/devenv.py", line 356, in main
    retcode = __call_conda_env_update(args, output_filename)
  File "/home/company/Work/miniconda/lib/python2.7/site-packages/conda_devenv/devenv.py", line 268, in __call_conda_env_update
    return subprocess.call(command)
  File "/home/company/Work/miniconda/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/company/Work/miniconda/lib/python2.7/subprocess.py", line 390, in _init_
    errread, errwrite)
  File "/home/company/Work/miniconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
After some time investigating I found out it was because I didn't have conda on PATH. I think it should either not require it to be on path (using absolute path instead) or give a better error message.

**Comment by gqmelo** [comment]
I agree ```conda-devenv``` should discover conda's absolute path, as ```conda``` does not require itself to be on ```PATH```
