### ISSUE TITLE
Support for pip on dependencies section

### ISSUE THREAD

**Issue by igortg** [ESSS/conda-devenv#55]
Having some like above on devenv.yml:
```
dependencies:
- wheel=0.29.0=py36_0
- pip:
  - fdb==1.6.1
```
throws the following error when calling `conda devenv`:
```
  File "C:\Miniconda3-x86\lib\re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Comment by prusse-martin** [comment]
Full stacktrace:

```
Traceback (most recent call last):
  File "W:\def\envs\v\Scripts\conda-devenv-script.py", line 5, in <module>
    sys.exit(conda_devenv.devenv.main())
  File "W:\def\envs\v\lib\site-packages\conda_devenv\devenv.py", line 389, in main
    conda_yaml_dict, environment = load_yaml_dict(filename)
  File "W:\def\envs\v\lib\site-packages\conda_devenv\devenv.py", line 149, in load_yaml_dict
    merged_dict = merge(all_yaml_dicts.values())
  File "W:\def\envs\v\lib\site-packages\conda_devenv\devenv.py", line 97, in merge
    merge_dependencies_version_specifications(final_dict)
  File "W:\def\envs\v\lib\site-packages\conda_devenv\devenv.py", line 113, in merge_dependencies_version_specifications
    m = re.match(package_pattern, dep)
  File "W:\def\envs\v\lib\re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

I guess this error was introduced in version 0.9.6. You could try 0.9.5 (that one worked for me).
Could you also say what version of conda are you using (and conda-env)?
